---
title: "working code for Hypothesis 1"
author: "Samuel Schappel"
date: "7/20/2021"
output: ioslides_presentation
---
```{r}
"Import reticulate to work between R and python as well as other packages"

library(reticulate)
use_virtualenv("r-reticulate")
py_available(TRUE)

```

```{python }
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import colors
from matplotlib.ticker import PercentFormatter

team_Data = pd.read_csv("Resources/teamData.csv")
player_Data = pd.read_csv("Resources/playerData.csv")
crossReference_Data = pd.read_csv("Resources/crossReference.csv")

merged_player_data = player_Data.loc[(player_Data['Year'] >= 1986) & (player_Data['Year'] < 2018)]
```

```{python}
hp1_subset_list = ['MP', '3P', '2P', 'FT', 'ORB', 'BLK', 'DRB', 'STL']
hp1_subset = merged_player_data[hp1_subset_list]
```

```{python}
Q1h=hp1_subset.quantile(0.25)
Q3h=hp1_subset.quantile(0.75)
IQRh=Q3h-Q1h

hp1_subset['ln_mp'] = np.log(hp1_subset['MP'])
hp1_subset['ln_ft'] = np.log(hp1_subset['FT'])
hp1_subset['ln_orb'] = np.log(hp1_subset['ORB'])
hp1_subset['ln_2p'] = np.log(hp1_subset['2P'])
hp1_subset['ln_3p'] = np.log(hp1_subset['3P'])
hp1_subset['ln_blk'] = np.log(hp1_subset['BLK'])
hp1_subset['ln_drb'] = np.log(hp1_subset['DRB'])
hp1_subset['ln_stl'] = np.log(hp1_subset['STL'])

hp1_subset_no = hp1_subset[~((hp1_subset<(Q1h-1.5*IQRh))) | ((hp1_subset>(Q3h+1.5*IQRh)))]

#hp1_subset_no = hp1_subset_no_na = hp1_subset_no.dropna().reset_index()

hp1_working_df = hp1_subset_no[hp1_subset_no.replace([np.inf, -np.inf], np.nan).notnull().all(axis=1)]
```

```{r}
hp1_working_df  <- py$hp1_working_df

reg_hp1 <- lm(hp1_working_df$ln_mp ~ hp1_working_df$ln_blk + hp1_working_df$ln_drb + hp1_working_df$ln_stl + hp1_working_df$ln_ft + hp1_working_df$ln_orb + hp1_working_df$ln_3p + hp1_working_df$ln_2p)
```

```{r}
summary(reg_hp1)
summary(reg_no_outlier)
options(max.print = 1000000)
options(scipen=999)
```


